sudo: required
services:
    - docker

before_install:
    - docker build -t client-test -f ./client/Dockerfile.dev ./client/

script:
    - docker run -e CI=true client-test npm run test -- --coverage

after_success:
    - docker build -t a1ku/multi-client ./client
    - docker build -t a1ku/multi-nginx ./nginx
    - docker build -t a1ku/multi-server ./server
    - docker build -t a1ku/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push a1ku/multi-client
    - docker push a1ku/multi-nginx
    - docker push a1ku/multi-server
    - docker push a1ku/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "multiple-containers"
    env: "MultipleContainers-env"
    bucket_name: "elasticbeanstalk-eu-west-1-906015301963"
    bucket_path: "multiple-containers"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    